# Generated by Django 5.2.8 on 2025-12-08 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='date',
            field=models.DateField(default=datetime.date(2025, 12, 8)),
        ),
    ]
