# Generated by Django 5.2.8 on 2025-12-22 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_alter_body_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='date',
            field=models.DateField(default=datetime.date(2025, 12, 22)),
        ),
    ]
