# Generated by Django 5.2.8 on 2025-12-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_alter_body_date'),
    ]

    operations = [
    ]
