# Generated by Django 5.2.8 on 2025-12-22 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_remove_sleep_date_alter_sleep_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
