# Generated by Django 5.2.8 on 2025-12-08 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
